### ISSUE TITLE
Problem running MindsDB with CrateDB

### ISSUE THREAD

**Issue by amotl** [crate/crate-clients-tools#49]
Hi there,

@hammerhead recently evaluated the [Forecasting Quarterly House Sales with MindsDB] tutorial with CrateDB and this Python driver (thanks!), so I would like to report about the outcome.

With kind regards,
Andreas.

### Report

> An error is thrown while computing the model, and the model is set to `failed`. The same example works well when using PostgreSQL.

```python
INFO:type_infer-6520:Analyzing a sample of 5
INFO:type_infer-6520:from a total population of 5, this is equivalent to 100.0% of your data.
INFO:type_infer-6520:Infering type for: saledate
INFO:type_infer-6520:Column saledate has data type categorical
INFO:type_infer-6520:Infering type for: ma
INFO:type_infer-6520:Column ma has data type binary
INFO:type_infer-6520:Infering type for: type
INFO:type_infer-6520:Column type has data type binary
INFO:type_infer-6520:Infering type for: bedrooms
INFO:type_infer-6520:Column bedrooms has data type binary
WARNING:type_infer-6520:Column saledate is an identifier of type "UUID"
WARNING:type_infer-6520:Column bedrooms is an identifier of type "No Information"
INFO:dataprep_ml-6520:Starting statistical analysis
INFO:dataprep_ml-6520:Dropping features: ['saledate']
Traceback (most recent call last):
  File "/path/to/mindsdb/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'saledate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/mindsdb/lib/python3.8/site-packages/mindsdb/integrations/libs/ml_exec_base.py", line 128, in learn_process
    ml_handler.create(target, df=training_data_df, args=problem_definition)
  File "/path/to/mindsdb/lib/python3.8/site-packages/mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py", line 67, in create
    run_learn(
  File "/path/to/mindsdb/lib/python3.8/site-packages/mindsdb/utilities/functions.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/path/to/mindsdb/lib/python3.8/site-packages/mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/functions.py", line 147, in run_learn
    run_generate(df, predictor_id, args)
  File "/path/to/mindsdb/lib/python3.8/site-packages/mindsdb/utilities/functions.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/path/to/mindsdb/lib/python3.8/site-packages/mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/functions.py", line 58, in run_generate
    json_ai = lightwood.json_ai_from_problem(df, problem_definition)
  File "/path/to/mindsdb/lib/python3.8/site-packages/lightwood/api/high_level.py", line 74, in json_ai_from_problem
    stats = statistical_analysis(
  File "/path/to/mindsdb/lib/python3.8/site-packages/dataprep_ml/insights.py", line 61, in statistical_analysis
    df = cleaner(data, dtypes, args.get('pct_invalid', 0),
  File "/path/to/mindsdb/lib/python3.8/site-packages/dataprep_ml/cleaners.py", line 57, in cleaner
    data = clean_timeseries(data, timeseries_settings)
  File "/path/to/mindsdb/lib/python3.8/site-packages/dataprep_ml/cleaners.py", line 397, in clean_timeseries
    if pd.isna(row[tss['order_by']]):
  File "/path/to/mindsdb/lib/python3.8/site-packages/pandas/core/series.py", line 942, in __getitem__
    return self._get_value(key)
  File "/path/to/mindsdb/lib/python3.8/site-packages/pandas/core/series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "/path/to/mindsdb/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'saledate'
```

[Forecasting Quarterly House Sales with MindsDB]: https://docs.mindsdb.com/sql/tutorials/house-sales-forecasting

**Comment by amotl** [comment]
Hi. The upstream issue has been closed as completed, but without any further information. Can we re-evaluate the situation?

-- https://github.com/mindsdb/mindsdb/issues/5483#event-11584077360

**Comment by hammerhead** [comment]
Hi,

I checked the commit history since the last time I looked at it, and I don't see any changes. The closing of the upstream issue probably has to be interpreted as "won't fix", since there are also no linked pull requests or anything else.

**Comment by amotl** [comment]
Thanks. Can you re-open the issue, and can we discuss it? I would like to use your insights to eventually submit a patch, when applicable. However, I haven't approached the topic yet, a concise minimal reproducer could help.

**Comment by amotl** [comment]
Dear @chandrevdw31,

thank you for submitting GH-118. Does that mean MindsDB works well together with CrateDB now?

As you can read from this discussion, we could not derive any clear outcome from https://github.com/mindsdb/mindsdb/issues/5483 ff., and did not re-evaluate the situation yet on our behalves.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Thank you very much, Chandre. Do you have any news to report about this matter?

/cc @hlcianfagna

**Comment by amotl** [comment]
Hi again. Hereby, let me also ping @kneth. Maybe he can team up with @chandrevdw31 to make a difference in resuming progress here?

- https://github.com/crate/crate-clients-tools/pull/118

**Comment by chandrevdw31** [comment]
@amotl Hey Andreas, apologies for the delay in response. We manually tested our Crate DB in October and all seems to be working. You can check out screen recordings in this [issue](https://github.com/mindsdb/mindsdb/issues/9935). Please let me know if you have further questions

**Comment by amotl** [comment]
Hi @chandrevdw31. Thank you so much.
We will keep this issue open until we derived a corresponding documentation page from this positive outcome.

**Comment by amotl** [comment]
We added a canonical documentation page on our side, referring to yours. Thank you again.

- https://cratedb.com/docs/guide/integrate/mindsdb/
